version: '3.8'

services:
  txapo_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - txapo_network

networks:
  txapo_network:
    driver: bridge
      
